### PR TITLE
Update inputmask and ember-cli

### PR DESCRIPTION
**Pull request by lucacorti**

### CODE REVIEW

**Comment by devotox** [comment]
What did you use to update ember CLI?

**Comment by lucacorti** [comment]
I just run yarn and `ember init`

**Comment by lucacorti** [comment]
Uh, sorry, I see something from a private npm repo slipped in. I'll fix yarn.lock in a minute.

**Comment by devotox** [comment]
Tests are failing. You may need to add ember try as a Dev dependency

**Comment by lucacorti** [comment]
Actually `ember-try` is in devDependencies, but complains about try:one needing a scenario. So it seems it is not picking up the `EMBER_TRY_SCENARIO` variable for some reason. `ember try:each` locally runs with only a test failure which is actually the linter complaining about `sendAction`.

**Comment by devotox** [comment]
I will help look into it as soon as possible

**Comment by devotox** [comment]
atm I have just done an easy update and released a new version. I may do a full update later using this PR as a base. Hopefully that should help

**Comment by lucacorti** [comment]
Yes, great. Thanks.

**Pull request closed without merging**
